-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

--Explore raw user data

SELECT * FROM json.`/Volumes/dbacademy/${schema}/c360/users`

-- COMMAND ----------

--Explore raw order data
SELECT * FROM json.`/Volumes/dbacademy/${schema}/c360/orders`

-- COMMAND ----------

--Explore raw event data

SELECT * FROM csv.`/Volumes/dbacademy/${schema}/c360/events`
